networks:
  lamenu:
    external: true
    name: lamenu

services:
  app:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order.rule=PathPrefix(`/order`)"
      - "traefik.http.routers.order.entrypoints=web"
      - "traefik.http.services.order.loadbalancer.server.port=80"
      # - "traefik.http.middlewares.order-strip-prefix.stripPrefix.prefixes=/order"
      # - "traefik.http.routers.order.middlewares=order-strip-prefix"
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/code
