networks:
  lamenu:
    external: true
    name: lamenu

volumes:
  pycache: null

services:
  payment:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=PathPrefix(`/payment`)"
      - "traefik.http.routers.payment.entrypoints=web"
      - "traefik.http.services.payment.loadbalancer.server.port=8000"
    networks:
      - lamenu
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - JWT_KEY=${JWT_KEY}
    volumes:
      - ./:/code
      - pycache:/var/cache/pycache
