networks:
  lamenu:
    external: true

volumes:
  pg_data: null
  pycache: null

services:
  user-nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=PathPrefix(`/user`)"
      - "traefik.http.routers.user.entrypoints=web"
      - "traefik.http.services.user.loadbalancer.server.port=80"
      - "traefik.http.middlewares.user-strip-prefix.stripPrefix.prefixes=/user"
      - "traefik.http.routers.user.middlewares=user-strip-prefix"
    networks:
      - lamenu
    volumes:
      - ./resources/layout/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/:/usr/share/nginx/html/resources/
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    depends_on:
      - user
  user:
    networks:
      - lamenu
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    restart: always
    command: ${COMMAND:-sh ./entrypoint.sh}
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
    volumes:
      - .:/code
      - pycache:/var/cache/pycache
    depends_on:
      - user-db
  user-db:
    networks:
      - lamenu
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '2309'
    volumes:
      - pg_data:/var/lib/postgresql/data
